# Generated by Django 6.0.2 on 2026-04-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0003_alter_enquiry_options_alter_enrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tools_covered',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
