# Generated by Django 6.0.2 on 2026-04-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0004_alter_course_tools_covered'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='emi_available',
            field=models.BooleanField(default=False, help_text='Check if EMI option is available for this course'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['emi_available'], name='course_emi_idx'),
        ),
    ]
