# Generated by Django 6.0.2 on 2026-04-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0005_course_emi_available_course_course_emi_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
    ]
