# Generated by Django 6.0.2 on 2026-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0008_course_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_numbers', models.CharField(help_text='Enter phone numbers separated by commas (e.g. 8438164827, 8438524427)', max_length=100)),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Numbers',
            },
        ),
    ]
