# Generated by Django 6.0.2 on 2026-04-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0009_contactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text="e.g., '8+', '5000+', '85%'", max_length=20)),
                ('label', models.CharField(help_text="e.g., 'Years of Excellence', 'Students Trained'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Determines the display order')),
            ],
            options={
                'verbose_name': 'Company Stat',
                'verbose_name_plural': 'Company Stats',
                'ordering': ['order'],
            },
        ),
    ]
