# Generated by Django 6.0.2 on 2026-04-07 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0010_companystat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'Feedback Videos', 'Success Stories'", max_length=100, unique=True)),
                ('order', models.IntegerField(default=0, help_text='Determines which section shows up first on the page')),
            ],
            options={
                'verbose_name': 'Story Section',
                'verbose_name_plural': 'Story Sections',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='studentstory',
            name='course_or_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentstory',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentstory',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='VTS.storysection'),
        ),
    ]
