# Generated by Django 6.0.2 on 2026-04-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0011_storysection_alter_studentstory_course_or_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentproject',
            name='project_link',
            field=models.URLField(blank=True, help_text='External link to the project (e.g., GitHub, live website)', max_length=500, null=True),
        ),
    ]
