# Generated by Django 6.0.2 on 2026-04-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0013_imagecategory_environmentimage_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(help_text='The main bold text', max_length=255)),
                ('description', models.TextField(help_text='The smaller paragraph text')),
                ('background_image', models.ImageField(upload_to='home_banners/')),
                ('is_active', models.BooleanField(default=False, help_text='Check this to display THIS banner on the homepage. Only one should be active.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Home Banner',
                'verbose_name_plural': 'Home Banners',
                'ordering': ['-created_at'],
            },
        ),
    ]
