# Generated by Django 6.0.2 on 2026-04-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0014_homebanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home_about/')),
                ('badge_title', models.CharField(help_text="e.g., 'Established in 2021'", max_length=100)),
                ('badge_description', models.TextField(help_text="e.g., 'Specializing in IT training...'")),
                ('main_heading', models.CharField(help_text="e.g., 'Why Choose Our Training Programs'", max_length=200)),
                ('main_description', models.TextField()),
                ('is_active', models.BooleanField(default=False, help_text='Check this to display THIS section on the homepage.')),
            ],
            options={
                'verbose_name': 'Home About Section',
                'verbose_name_plural': 'Home About Sections',
            },
        ),
    ]
