# Generated by Django 6.0.2 on 2026-04-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0015_homeaboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBenefitSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Key Benefits', max_length=50)),
                ('image', models.ImageField(help_text='The illustration on the left', upload_to='home_benefits/')),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section on the homepage')),
            ],
            options={
                'verbose_name': 'Home Benefit Section',
                'verbose_name_plural': 'Home Benefit Sections',
            },
        ),
        migrations.CreateModel(
            name='BenefitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('users', 'Users / Team'), ('video', 'Video / Live Class'), ('briefcase', 'Briefcase / Practical'), ('trending', 'Trending / Career'), ('heart', 'Heart / Mentorship'), ('badge', 'Badge / Certification'), ('check', 'Checkmark (Default)')], default='check', max_length=20)),
                ('title', models.CharField(help_text="e.g., 'Industry-Experienced Trainers'", max_length=100)),
                ('description', models.CharField(help_text='Keep it short and punchy.', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears (1, 2, 3...)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='VTS.homebenefitsection')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
