# Generated by Django 6.0.2 on 2026-04-08 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0016_homebenefitsection_benefitcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProcessSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How Our Training Works', max_length=200)),
                ('subtitle', models.TextField(default='Follow our proven 4-step journey to transform from a beginner into an industry-ready tech professional.')),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section on the homepage')),
            ],
            options={
                'verbose_name': 'Home Process Section',
                'verbose_name_plural': 'Home Process Sections',
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(help_text='1, 2, 3, or 4')),
                ('title', models.CharField(help_text="e.g., 'Register'", max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon_image', models.ImageField(help_text='Upload a small PNG icon', upload_to='process_icons/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='VTS.homeprocesssection')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
    ]
