# Generated by Django 6.0.2 on 2026-04-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0017_homeprocesssection_processstep'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_heading', models.CharField(default='About Vetri Training – Online IT Courses with Placement Support', max_length=200)),
                ('sub_heading', models.TextField(default='Empowering the next generation of IT Professionals with foundational knowledge and industry - ready skills')),
                ('story_heading', models.CharField(default='Our Story – Building Job-Oriented Training Programs', max_length=200)),
                ('paragraph_1', models.TextField()),
                ('paragraph_2', models.TextField(blank=True, help_text='Optional second paragraph', null=True)),
                ('image', models.ImageField(help_text='Upload the main collaboration image', upload_to='about_pages/')),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this on the website')),
            ],
            options={
                'verbose_name': 'About Page Section',
                'verbose_name_plural': 'About Page Sections',
            },
        ),
    ]
