# Generated by Django 6.0.2 on 2026-04-08 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0018_aboutpagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_title', models.CharField(default='Mission', max_length=100)),
                ('mission_text', models.TextField(help_text='Text for the Mission card')),
                ('mission_icon', models.ImageField(help_text='Upload the Mission target icon', upload_to='about_icons/')),
                ('vision_title', models.CharField(default='Vision', max_length=100)),
                ('vision_text', models.TextField(help_text='Text for the Vision card')),
                ('vision_icon', models.ImageField(help_text='Upload the Vision bulb icon', upload_to='about_icons/')),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section on the About page')),
            ],
            options={
                'verbose_name': 'Mission & Vision Section',
                'verbose_name_plural': 'Mission & Vision Sections',
            },
        ),
    ]
