# Generated by Django 6.0.2 on 2026-04-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0019_aboutmissionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_badge_text', models.CharField(default='The Complete VETRI Ecosystem', max_length=100)),
                ('main_image', models.ImageField(help_text='The large illustration on the left', upload_to='ecosystem/')),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section')),
            ],
            options={
                'verbose_name': 'Ecosystem Section',
                'verbose_name_plural': 'Ecosystem Sections',
            },
        ),
        migrations.CreateModel(
            name='EcosystemBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='ecosystem_logos/')),
                ('title', models.CharField(help_text="e.g., 'Vetri Technology Solution (VTS)'", max_length=100)),
                ('link_url', models.CharField(help_text="e.g., '/' or 'https://google.com'", max_length=200)),
                ('link_text', models.CharField(default='Site', max_length=20)),
                ('bullet_1', models.CharField(max_length=100)),
                ('bullet_2', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0, help_text='Order (1, 2, 3)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='VTS.ecosystemsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
