# Generated by Django 6.0.2 on 2026-04-08 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0020_ecosystemsection_ecosystembranch'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutApproachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Our Job-Oriented Training Approach', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section on the page')),
            ],
            options={
                'verbose_name': 'Training Approach Section',
                'verbose_name_plural': 'Training Approach Sections',
            },
        ),
        migrations.CreateModel(
            name='AboutApproachCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The paragraph text inside the card')),
                ('order', models.IntegerField(default=0, help_text='Order (1, 2, 3...)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='VTS.aboutapproachsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
