# Generated by Django 6.0.2 on 2026-04-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0021_aboutapproachsection_aboutapproachcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerSkillsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='How We Build Your Career Skills', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section')),
            ],
            options={
                'verbose_name': 'About Skills Section',
                'verbose_name_plural': 'About Skills Sections',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutapproachsection',
            options={'verbose_name': 'About Approach Section', 'verbose_name_plural': 'About Approach Sections'},
        ),
        migrations.CreateModel(
            name='CareerSkillCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('platform', 'Monitor / Platform'), ('approach', 'Network / Steps'), ('connection', 'Clipboard / Industry')], default='platform', max_length=20)),
                ('title', models.CharField(help_text="e.g., 'About the Training Platform'", max_length=100)),
                ('bullet_1', models.CharField(max_length=100)),
                ('bullet_2', models.CharField(max_length=100)),
                ('bullet_3', models.CharField(max_length=100)),
                ('bullet_4', models.CharField(blank=True, help_text='Optional 4th bullet', max_length=100, null=True)),
                ('order', models.IntegerField(default=0, help_text='1, 2, or 3')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='VTS.careerskillssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
