# Generated by Django 6.0.2 on 2026-04-08 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0022_careerskillssection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='"Your Learning & Career Journey"', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section')),
            ],
            options={
                'verbose_name': 'About Journey Section',
                'verbose_name_plural': 'About Journey Sections',
            },
        ),
        migrations.CreateModel(
            name='JourneyStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Entry & Counseling'", max_length=100)),
                ('description', models.CharField(max_length=150)),
                ('image', models.ImageField(help_text='Upload the step illustration', upload_to='journey_steps/')),
                ('order', models.IntegerField(default=0, help_text='1, 2, 3, 4, 5, 6')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='VTS.journeysection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
