# Generated by Django 6.0.2 on 2026-04-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0023_journeysection_journeystep'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Who Can Enroll in Our Courses', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this section')),
            ],
            options={
                'verbose_name': 'About Enrollment Section',
                'verbose_name_plural': 'About Enrollment Sections',
            },
        ),
        migrations.CreateModel(
            name='TargetAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Students', 'Career Switchers'", max_length=100)),
                ('image', models.ImageField(help_text='Upload the portrait image', upload_to='enrollment_images/')),
                ('theme_color', models.CharField(choices=[('#FF9C00', 'Orange'), ('#6C2CB1', 'Purple')], default='#FF9C00', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='1, 2, 3, 4, 5')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to='VTS.enrollmentsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
