# Generated by Django 6.0.2 on 2026-04-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0024_enrollmentsection_targetaudience'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTABanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Ready to Start Your Career', max_length=150)),
                ('description', models.TextField(help_text='The text below the title')),
                ('image', models.ImageField(help_text='Upload the circular profile/avatar image', upload_to='cta_banners/')),
                ('button_text', models.CharField(default='Get Free Consultation Now', max_length=50)),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this banner on the page')),
            ],
            options={
                'verbose_name': 'About CTA Banner',
                'verbose_name_plural': 'About CTA Banners',
            },
        ),
    ]
