# Generated by Django 6.0.2 on 2026-04-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0025_ctabanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningJourneyCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Start your Learning Journey today !', max_length=200)),
                ('description', models.TextField(help_text='The subtitle text')),
                ('button_text', models.CharField(default='Get Free Consultation', max_length=50)),
                ('image', models.ImageField(help_text='Upload the cutout person image (PNG with transparent background recommended)', upload_to='cta_images/')),
                ('is_active', models.BooleanField(default=False, help_text='Check to display this banner on the page')),
            ],
            options={
                'verbose_name': 'Home Learning Journey CTA',
                'verbose_name_plural': 'Home Learning Journey CTAs',
            },
        ),
    ]
