# Generated by Django 6.0.2 on 2026-04-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0026_learningjourneycta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Office Hours', 'Phone Number'", max_length=100)),
                ('icon', models.CharField(choices=[('clock', 'Clock (Office Hours)'), ('phone', 'Phone (Call Us)'), ('mail', 'Envelope (Email)'), ('location', 'Map Pin (Address)')], default='clock', max_length=20)),
                ('details', models.TextField(help_text='Press Enter to create a new line.')),
                ('order', models.IntegerField(default=0, help_text='1, 2, 3...')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Info Card',
                'verbose_name_plural': 'Contact Info Cards',
                'ordering': ['order'],
            },
        ),
    ]
