# Generated by Django 6.0.2 on 2026-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0027_contactinfocard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brochure Lead',
                'verbose_name_plural': 'Brochure Leads',
                'ordering': ['-downloaded_at'],
            },
        ),
    ]
