# Generated by Django 6.0.2 on 2026-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0029_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='benefit_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='learn_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
