# Generated by Django 6.0.2 on 2026-04-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0030_course_benefit_title_course_learn_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentimage',
            options={'ordering': ['order'], 'verbose_name': 'Contact Environment Image & video', 'verbose_name_plural': 'Contact Environment Image & video'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='benefit_title',
        ),
        migrations.RemoveField(
            model_name='course',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learn',
        ),
        migrations.RemoveField(
            model_name='course',
            name='learn_title',
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='environmentimage',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='environmentimage',
            name='video',
            field=models.FileField(blank=True, help_text='Upload .mp4 or .webm files here', null=True, upload_to='learning_environment/videos/'),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Description for image, or title for video', max_length=255),
        ),
        migrations.AlterField(
            model_name='environmentimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='learning_environment/images/'),
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text="e.g., 'Do I need coding knowledge?'", max_length=255)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='VTS.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Skills You will Gain in Python FullStack'", max_length=150)),
                ('top_icon', models.ImageField(blank=True, null=True, upload_to='course_card_icons/')),
                ('order', models.IntegerField(default=0, help_text='Order in which the column appears (1, 2, 3...)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='VTS.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseFeatureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('list_icon', models.ImageField(blank=True, null=True, upload_to='course_item_icons/')),
                ('order', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='VTS.coursefeaturecard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
