# Generated by Django 6.0.2 on 2026-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0031_alter_environmentimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional: e.g., Tirunelveli Branch', max_length=100)),
                ('address_lines', models.TextField(help_text='Full address. Use Enter for new lines.')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers show up first')),
            ],
            options={
                'verbose_name': 'Office Address',
                'verbose_name_plural': 'Office Addresses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='© 2026 All Rights Reserved By DITRP', max_length=255)),
                ('footer_logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
