# Generated by Django 6.0.2 on 2026-04-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VTS', '0032_officeaddress_sitesettings_alter_coursecategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='banner_text',
            field=models.CharField(default="India's First IT Training Institute with 100% Placement 👍", max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='primary_phone',
            field=models.CharField(default='8438164827', help_text='Phone number for the top header', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Main header logo', null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='VETRI TECHNOLOGY SOLUTIONS', max_length=100),
        ),
    ]
